DROP TABLE IF EXISTS skills;

CREATE TABLE skills (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    added TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    years_of_experience INTEGER NOT NULL,
    name  TEXT NOT NULL
);

